spring:
  application:
    name: pubsub-publisher
  cloud:
    gcp:
      project-id: YOUR-GCP-PROJECT-ID-HERE
      pubsub:
        emulator-host: localhost:8681
server:
  port : 8082
aims:
  pubsub:
    topic: new-address